# Generated by Django 3.1.3 on 2020-12-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='deposit_amount_en_us',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_amount_es',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_amount_ne',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_amount_ru',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='review_en_us',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='review_es',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='review_ne',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='review_ru',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
