# Generated by Django 3.1.3 on 2020-12-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_auto_20201205_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='deposit_amount_es',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='deposit_amount_ru',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='review_es',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='review_ru',
        ),
    ]
