# Generated by Django 3.1.4 on 2020-12-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_auto_20201207_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='deposit_amount_en_us',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='deposit_amount_ne',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='review_en_us',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='review_ne',
        ),
    ]
