# Generated by Django 3.1.4 on 2020-12-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0006_auto_20201216_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='photo',
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_Image',
            field=models.ImageField(blank=True, null=True, upload_to='deposit_photos/'),
        ),
    ]
