# Generated by Django 3.1.4 on 2020-12-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0007_auto_20201216_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='deposit_Image',
            new_name='photo',
        ),
    ]
