# Generated by Django 3.1.3 on 2020-11-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('detail', models.TextField(blank=True, max_length=5000, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catagories_photos/', verbose_name='Add image (optional)')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('email', models.CharField(db_index=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catagories_photos/', verbose_name='Add image (optional)')),
                ('number', models.CharField(db_index=True, max_length=150)),
                ('facebook', models.CharField(db_index=True, max_length=150)),
            ],
        ),
    ]
