# Generated by Django 3.1.3 on 2020-12-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
