# Generated by Django 3.1.3 on 2020-12-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_messagemodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_index=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('question', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
