# Generated by Django 3.1.3 on 2020-12-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pw',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
