# Generated by Django 3.1.3 on 2020-12-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
