# Generated by Django 3.1.4 on 2020-12-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forzza_password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='forzza_username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
